### ISSUE TITLE
Table: Compact

### ISSUE THREAD

**Issue by eshiol** [italia/design-web-toolkit#106]
Tutte le tabelle sono definite nella forma
```
<table class="">
    <caption class="u-hiddenVisually"></caption>
```
tranne la Compact nella quale è stato valorizzato l'attributo aria-describerby e manca il tag caption
```
<table class="" aria-describedby="">
```
si tratta di un refuso o c'è un motivo particolare?

**Comment by gunzip** [comment]
è un modo alternativo di descrivere i contenuti della tabella:
https://www.w3.org/WAI/tutorials/tables/caption-summary/
volendo possiamo allinearlo agli altri tpl e usare una caption.
