### ISSUE TITLE
Bug: componente leads con barre di scorrimento

### ISSUE THREAD

**Issue by robertogallea** [italia/design-web-toolkit#114]
Sia in Chrome che in Firefox, il componente leads (anche nell'esempio della documentazione), presenta delle bare di scorrimento orizzontali.

**Comment by gunzip** [comment]
puoi fornire un esempio ?

qui il componente è visibile a fondo pagina ma non vedo le barre di scorrimento:
https://italia.github.io/design-web-toolkit/components/preview/page--default.html

**Comment by robertogallea** [comment]
Anche nella pagina di descrizione del componente

https://italia.github.io/design-web-toolkit/components/preview/leads.html

Probabilmente il problema si verifica se non si include all'interno di un container con larghezza limitata?

**Comment by gunzip** [comment]
si esatto, è un comportamento atteso. è dovuto in generale al fatto che i singoli componenti non impostano margini e padding poiché questi vengono impostati dai contenitori.

**Comment by robertogallea** [comment]
Ok, chiarito, grazie.
