### ISSUE TITLE
tema wordpress

### ISSUE THREAD

**Issue by marcobr1** [italia/design-web-toolkit#116]
ciao,
ad oggi esiste un tempa wp (oppure joomla) da cui partire per la creazione di un sito web comunale?
grazie!

**Comment by francescozaia** [comment]
Ciao @marcobr1,
non c'è ancora qualcosa di pronto e completo, puoi trovare un po' di informazioni a riguardo su alcune discussioni sul Forum di Developers Italia (ad esempio [qui](https://forum.italia.it/t/tema-per-wordpress/775) e [qui](https://forum.italia.it/t/joomla-e-pa-template/1194)).

Nel caso in futuro volessi un update, o meglio ancora contribuire con una pull request, puoi fare riferimento a questi repo:
- https://github.com/italia/design-wordpress-theme
- https://github.com/italia/design-joomla-theme

**Comment by ruphy** [comment]
Closing as duplicate of https://github.com/italia/design-wordpress-theme/issues/1
