### ISSUE TITLE
"Accedi ai servizi": dov'è?

### ISSUE THREAD

**Issue by jdeyla** [italia/design-web-toolkit#119]
Non è una questione tecnica, l'ho aperta anche sul [forum .it](https://forum.italia.it/u/account-created), ma anche qui ci sono menti brillanti che potrebbero trovare una soluzione.

I Comuni (es. Biella e Venezia) hanno in alto a destra "Accedi ai servizi", nel Kit è sparito, a destra in alto, c'è la lingua.

Ce lo siamo perso, non serve più o ha cambiato posto?

**Comment by francescozaia** [comment]
In discussione sul forum di Developers Italia a [questo thread](https://forum.italia.it/t/template-designer-italia-e-progetti-europei-come-fare/1794), qui chiudo.
