### ISSUE TITLE
Logo UE

### ISSUE THREAD

**Issue by jdeyla** [italia/design-web-toolkit#120]
Il Logo UE è obbligatorio che sia visibile nella prima schermata, senza scroll e su qualsiasi dispositivo.
http://eur-lex.europa.eu/legal-content/IT/TXT/HTML/?uri=CELEX:32014R0821&from=IT

Dove lo si mette nei siti compliant questo kit?
Si segue l'esempio di http://www.lavoro.gov.it/Pagine/default.aspx 
Non sarebbe il posto de cambio lingua, e non starebbe meglio in alto a sinistra, dove c'è il lnk all' "entità" superiore?
Vale la pena metterlo nel kit?

**Comment by pdavide** [comment]
Ciao @jdeyla,
il regolamento UE al quale ti riferisci mi sembra che si riferisca ai siti relativi a progetti finanziati con fondi comunitari. O sbaglio?
Siti come http://www.istruzione.it/pon/ o http://www.pongovernance1420.gov.it/it/ dovrebbero essere quelli soggetti all'obbligo di presenza del logo UE above-the-fold.
Al di là della questione specifica del logo UE, potrebbe essere utile aprire un confronto sul tema di un "secondary logo", ma direi di spostare la discussione sul [repo delle linee guida](https://github.com/italia/design-docs).

**Comment by jdeyla** [comment]
ciao @pdavide apro le solite mie issue del venerdì pomeriggio. Parlo di siti sui fondi europei e siti di progetti finanziati dall'Europa. Nel nostro caso dobbiamo migrare ad AGID il sito del POR-FESR. e come noi tutte le Regioni avranno questo problema.
Sposta dove pensi sia meglio, io lo vedo bene in entrambi

**Comment by pdavide** [comment]
Issue [spostata](https://github.com/italia/design-docs/issues/58) sul repo delle linee guida.
