### ISSUE TITLE
Compatibilità componenti dinamiche con IE8

### ISSUE THREAD

**Issue by lellorav83** [italia/design-web-toolkit#123]
Buongiorno,
ho provato a testare qualche componente dinamico attingendo dal design-web-toolkit
(https://italia.github.io/design-web-toolkit/components). Risulta anche a voi che componenti come 
Megamenu, Dropdown, Accordion, Carousel, Datepicker non funzionano con IE8 oppure sono io che sbaglio qualcosa?

Grazie

**Comment by gunzip** [comment]
ciao @lellorav83 il supporto del TK è >= IE10 (quello per IE8 è obsoleto), lo stesso indicato nei testi delle linee guida: http://design-italia.readthedocs.io/it/latest/doc/user-interface/principi.html

**Comment by lellorav83** [comment]
Grazie per la risposta, quindi dal link deduco che, essendo un "Si deve", tutti i portali per la Pubblica Amministrazione realizzati da qui in avanti dovranno necessariamente essere responsive per aderire alle linee guida AGID, corretto?

**Comment by gunzip** [comment]
affermativo. diciamo che, nel caso specifico della fruibilità da mobile, "per aderire alle linee guida" è un motivo secondario rispetto a "per venire incontro alle esigenze dei cittadini" :)
