### ISSUE TITLE
Font Titillium Web

### ISSUE THREAD

**Issue by mbolzan** [italia/design-web-toolkit#58]
Volevo segnalare che l'utilizzo del font Titillium Web su browser Firefox (io ho testato v.45) ha diversi problemi di definizione delle lettere, soprattutto le maiuscole S o G.
su Chrome invece molto meglio.

la distorsione sembra quasi un aliasing delle immagini, vi risulta ?

**Comment by gunzip** [comment]
@mbolzan su quale sistema operativo ? puoi allegare alla issue uno screenshot che mostri il problema ?

**Comment by mbolzan** [comment]
SO: win 7 PRO
allego un paio di screenshot, non rende molto nella jpg ma vi assicuro che è evidente su quasi tutto il testo la sbavatura sotto le lettere grandi o nelle lettere piccole come la zz del menu laterale

![ss_titillium_font](https://cloud.githubusercontent.com/assets/1257560/23403486/a1eca184-fdb0-11e6-8240-0a3a28e7e630.jpg)
![ss_titillium_font2](https://cloud.githubusercontent.com/assets/1257560/23403487/a1ee6d34-fdb0-11e6-95f2-806c50a69112.jpg)

**Comment by gunzip** [comment]
confermo, anche sul sito di FP e governo, con win7 e firefox da problemi di rendering, 
IE e chrome invece ok.

![image](https://cloud.githubusercontent.com/assets/148224/23408525/9f43be6e-fdc8-11e6-97f3-dfa6246ff28c.png)

![image](https://cloud.githubusercontent.com/assets/148224/23408578/d3cef630-fdc8-11e6-9662-627546b2f774.png)

**Comment by AlessandroVecchi** [comment]
Uso firefox da sempre (attualmente su win 10) ma non replico questo problema.
Se c'è un browser che di solito ha questi problemi di definizione dei caratteri e delle immagini è IE11

**Comment by equinusocio** [comment]
È un problema conosciuto di windows sul rendering dei font.

**Comment by zetareticoli** [comment]
In ogni caso è un font che ha seri problemi di leggibilità.

**Comment by andreacritelli** [comment]
Ho fatto alcuni test caricando il sito del web toolkit con le versioni dalla 45 alla 57 del browser Firefox e ho verificato che dalla 52 il rendering del font Titillium è nettamente migliorato.

**Comment by francescozaia** [comment]
Ottimo, direi che vista l'analisi fatta e dato che le nuove versioni di Firefox sembrano comportarsi meglio, qui possiamo chiudere.

Per discussioni di dettaglio su Titillium, possiamo usare [Slack](https://slack.developers.italia.it/) o il [Forum](https://forum.italia.it/) di Developers Italia
