### ISSUE TITLE
Il componente Treeview non funzione con l'ultima versione jquery

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/design-web-toolkit#96]
Ciao,
Ho aggiornato oggi il mio progetto alla v3.2.1 di jquery e il treeview non funziona più.
Prima usavo la 3.0.0 e funzionava.
La mia versione del codice che avevo prelevato dal webtoolkit risale a qualche mese fa, in ogni caso vedo che la versione usata nel demo https://italia.github.io/ita-web-toolkit/components/preview/treeview--default.html è ancora la 1.11.x

**Comment by gunzip** [comment]
dovrebbe andare adesso.

**Comment by AlessandroVecchi** [comment]
Ma hai aggiornato il codice del componente?

**Comment by gunzip** [comment]
si: https://github.com/italia/design-web-toolkit/commit/ae4ed05b641408a294fd819a4b96b6e97f14ebbc

**Comment by AlessandroVecchi** [comment]
Ok, una modifica minima, posso farla direttamente sul mio senza riesportare il componente.
Grazie
